apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashudb
  name: ashudb # name of deployment 
spec:
  replicas: 1 # number of DB pods 
  selector:
    matchLabels:
      app: ashudb
  strategy: {}
  template: # template to create DB POD 
    metadata:
      creationTimestamp: null
      labels: # label of pod 
        app: ashudb
    spec:
      volumes: # to create volume 
      - name: ashudbvol
        hostPath: # taking storage from Minion Node 
         path: /ashudata
         type: DirectoryOrCreate 
      containers:
      - image: mysql:5.6
        name: mysql
        env: # set / create ENV variable in POD 
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom: # calling value 
           secretKeyRef: # from secret 
            name: ashudbsec # name of secret 
            key: sqlpass  # key of secret 
        volumeMounts: # to mount storage we created above 
        - name: ashudbvol
          mountPath: /var/lib/mysql/ 
        resources: {}
status: {}
# creating secret 
---
apiVersion: v1
data:
  sqlpass: T3JhY2xldHIwOTk=
kind: Secret
metadata:
  creationTimestamp: null
  name: ashudbsec

# creating clusterIP type service to anything which is not exposable to outside
# world 
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashudb
  name: ashudb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: ashudb
  type: ClusterIP
status:
  loadBalancer: {}
# webapp 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashuwebapp
  name: ashuwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashuwebapp
  strategy: {}
  template: # template of POD 
    metadata:
      creationTimestamp: null
      labels:
        app: ashuwebapp
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env: # using env to connect DB 
        - name: WORDPRESS_DB_HOST
          value: ashudb # service name of DB deployment 
        - name: WORDPRESS_DB_PASSWORD
          valueFrom: # reading DB password from Secret 
           secretKeyRef:
            name: ashudbsec # name of secret 
            key: sqlpass # key of secret 
        resources: {}
status: {}
# creating service for deploy webapp
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashuwebapp
  name: ashuwebapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ashuwebapp
  type: LoadBalancer
status:
  loadBalancer: {}
